# Site settings
title: My Awesome GitHub Page
description: A description of your site
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://yourusername.github.io" # Your site URL
author: Your Name

# Theme settings
theme: jekyll-theme-cayman # Example theme, you can choose other themes
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation settings (for some themes)
navbar:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Blog
    link: /blog
  - name: Contact
    link: /contact

# Build settings
markdown: kramdown
highlighter: rouge

# Custom settings
social_links:
  twitter: your_twitter_username
  github: your_github_username
  linkedin: your_linkedin_username

# Other optional settings
paginate: 5 # Number of posts per page
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

# SEO settings
title_separator: "-"
