title: "Your Name - Professional Resume"
description: "A professional resume showcasing experience, skills, and projects."
theme: jekyll-theme-minimal # or choose a custom theme
url: "https://yourusername.github.io/my-professional-resume"
baseurl: "/my-professional-resume"
author: Your Name

# Navigation
navbar:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Experience"
    link: "/experience"
  - name: "Projects"
    link: "/projects"
  - name: "Education"
    link: "/education"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
social_links:
  linkedin: "your-linkedin-profile"
  github: "your-github-profile"
  twitter: "your-twitter-profile"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
